### ISSUE TITLE
Python error when rotating the Gizmo

### ISSUE THREAD

**Issue by L0Lock** [L0Lock/GizmoTools#2]
**Blender Version**
Broken: 3.2.0

**Short description of error**
Calling any Gizmo rotation function returns the following error:

```python
Python: Traceback (most recent call last):
  File "C:\AppInstall\Blender\MyScripts\addons\Gizmo Tools\__init__.py", line 273, in execute
    ot(value=addon_prefs.rinc, orient_axis='Y', orient_type='LOCAL')
  File "C:\AppInstall\Blender\stable\blender-3.2.0+stable.e05e1e369187\3.2\scripts\modules\bpy\ops.py", line 115, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.transform.rotate.poll() failed, context is incorrect
```

**Comment by L0Lock** [comment]
Fixed in 6c91458
